# Test
apiVersion: v1
kind: Namespace
metadata:
  name: kube-autogpt
---
apiVersion: v1
kind: Secret
metadata:
  name: openai-api-key
  namespace: kube-autogpt
type: Opaque
data:
  api-key: xxx
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-autogpt-operator
  namespace: kube-autogpt
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-autogpt-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: kube-autogpt-operator
    namespace: kube-autogpt
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-autogpt-operator
  namespace: kube-autogpt
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kube-autogpt-operator
  template:
    metadata:
      labels:
        name: kube-autogpt-operator
    spec:
      serviceAccountName: kube-autogpt-operator
      containers:
        - name: kube-autogpt-operator
          image: ronak08/kubeautogpt:v5
          imagePullPolicy: Always
          env:
            - name: GPT_MODEL
              value: gpt-3.5-turbo-0301
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: openai-api-key
                  key: api-key
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kube-autogpt-operator
  namespace: kube-autogpt
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: kube-autogpt-operator
    namespace: kube-autogpt
---